### ISSUE TITLE
GetLanguagesAsync only returns 2-letters Lang code

### ISSUE THREAD

**Issue by Licantrop0** [DotNetToscana/TranslatorService#1]
Hi Marco,
can you edit your GetLanguagesAsync to return a dictionary of LanguageName / LanguageCode like in this example? https://github.com/MicrosoftTranslator/CSharp-WPF-Example/blob/master/MSTranslatorTAPDemo/MainWindow.xaml.cs (see GetLanguageNamesMethod)

**Comment by marcominerva** [comment]
Good idea. I'm working on it!

**Comment by marcominerva** [comment]
Done. Look for the **GetLanguageNames** method :-) I'll update the NuGet packages in the next few days.

**Comment by Licantrop0** [comment]
Thanks!
